[project]
name = "pixi-cpp-meson"
version = "0.1.0"
description = "Add a short description here"
authors = ["Aleks Rūtiņš <aleks@rutins.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
configure = { cmd = [
    "meson",
    "setup",
    ".build"
] }

build = { cmd = ["meson", "compile", "-C", ".build"], depends_on = ["configure"] }

start = "./build/pixi_cpp_meson"

[dependencies]
cxx-compiler = "1.7.0.*"
meson = "1.3.0.*"
ninja = "1.11.1.*"
