[project]
name = "pixi-python"
version = "0.1.0"
description = "Add a short description here"
authors = ["Aleks Rūtiņš <aleks@rutins.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
start = "python -m flask run --port=3000"

[dependencies]
flask = "3.0.0.*"
python = "3.12.0.*"
